---
swagger: "2.0"
info:
  description: "Mail REST API"
  version: "1.0.0"
  title: "Mail REST API"
host: "172.16.1.249:8080"
basePath: "/mail"
tags:
- name: "mails"
  description: "mail collection"
schemes:
- "http"
paths:
  /mails:
    post:
      tags:
      - "mails"
      summary: "Add a new mail"
      description: ""
      operationId: "addmail"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "mail data"
        required: true
        schema:
          $ref: "#/definitions/mail"
      responses:
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.mails_controller"
  /mails/{mailId}:
    get:
      tags:
      - "mails"
      summary: "Find mail by ID"
      description: "Returns a single mail"
      operationId: "getmail_by_id"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "mailId"
        in: "path"
        description: "ID of mail to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/mail"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "mail not found"
      x-swagger-router-controller: "swagger_server.controllers.mails_controller"
    put:
      tags:
      - "mails"
      summary: "Updates an mail in the store with form data"
      description: ""
      operationId: "updatemail_with_form"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "mailId"
        in: "path"
        description: "ID of mail that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "sender"
        in: "formData"
        description: "Updated sender of the mail"
        required: false
        type: "string"
      - name: "receiver"
        in: "formData"
        description: "Updated receiver of the mail"
        required: false
        type: "string"
      - name: "mailText"
        in: "formData"
        description: "Updated text of the mail"
        required: false
        type: "string"
      responses:
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.mails_controller"
    delete:
      tags:
      - "mails"
      summary: "Deletes an mail"
      description: ""
      operationId: "deletemail"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "mailId"
        in: "path"
        description: "mail id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "mail not found"
      x-swagger-router-controller: "swagger_server.controllers.mails_controller"
    post:
      tags:
      - "mails"
      summary: "Add a new mail"
      description: ""
      operationId: "updatemail"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "mailId"
        in: "path"
        description: "mail id to delete"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "mail data"
        required: true
        schema:
          $ref: "#/definitions/mail"
      responses:
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.mails_controller"
definitions:
  mail:
    type: "object"
    required:
    - "id"
    - "mailText"
    - "receiver"
    - "sender"
    properties:
      id:
        type: "integer"
        format: "int64"
      sender:
        type: "string"
        example: "Jim"
      receiver:
        type: "string"
        example: "Jim"
      mailText:
        type: "string"
        example: "Hello world!"
    xml:
      name: "mail"
    example:
      receiver: "Jim"
      sender: "Jim"
      mailText: "Hello world!"
      id: 0
